version: '3.8'
services:
  db:
    image: postgres:14.4
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=todo
    ports:
      - '5431:5431'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      #- ./db/init.sql:/docker-entrypoint-initdb.d/createDB.sql

  api:
    container_name: todo-api
    build:
      context: ./
    image: todo-api
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      spring.datasource.url: jdbc:postgresql://localhost:5431/todo
      spring.datasource.username: postgres
      spring.datasource.password: postgres
      spring.jpa.hibernate.ddl-auto: update
      spring.jpa.show-sql: true
      spring.jpa.properties.hibernate.format_sql: true
      spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL81Dialect
     # NODE_ENV: production
     # DB_HOST: db
      #DB_PORT: 5432
      #DB_USER: postgres
      #DB_PASSWORD: postgres
      #DB_NAME: todo
    links:
      - db
      
volumes:
  db:
    driver: local